package com.ecommerceapplication.ecommeceapp.dto;

import com.ecommerceapplication.ecommeceapp.constant.UserType;
import com.ecommerceapplication.ecommeceapp.entity.Seller;
import com.ecommerceapplication.ecommeceapp.entity.User;
import lombok.*;

import java.time.Instant;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class SellerDTO {

    private Integer sellerId;
    private Integer userId;
    private String companyName;
    private String gstIn;

    private String ownerName;
    private String userName;
    private String password;
    private Long mobileNo;

    // Converts Seller entity to SellerDTO
    public static SellerDTO toDTO(Seller seller) {
        return new SellerDTO(
                seller.getSellerId(),
                seller.getUser().getUserId(),
                seller.getCompanyName(),
                seller.getGstIn(),
                seller.getUser().getName(),
                seller.getUser().getUserName(),
                seller.getUser().getPassword(),
                seller.getUser().getMobileNo()
        );
    }

    // Converts SellerDTO to Seller entity
    public static Seller toSeller(SellerDTO sellerDTO, User user) {
        return new Seller(
                user,
                sellerDTO.getSellerId(),
                sellerDTO.getCompanyName(),
                sellerDTO.getGstIn()
        );
    }

    // Converts SellerDTO to User entity (for registration)
    public User toUser() {
        return new User(
                null, // User ID (auto-generated by DB)
                this.ownerName,
                this.password,
                this.ownerName,
                UserType.SELLER, // Assuming UserType enum has a SELLER value
                this.userName,
                this.mobileNo
        );
    }
}
