package com.ecommerceapplication.ecommeceapp.dto;

import com.ecommerceapplication.ecommeceapp.constant.UserType;
import com.ecommerceapplication.ecommeceapp.entity.Seller;
import com.ecommerceapplication.ecommeceapp.entity.SubUser;
import com.ecommerceapplication.ecommeceapp.entity.User;
import lombok.*;

import java.util.List;
import java.util.stream.Collectors;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class SellerDTO {

    private Integer sellerId;
    private Integer userId;
    private String companyName;
    private String gstIn;

    private String ownerName;
    private String userName;
    private String password;
    private Long mobileNo;

    // Add a list of subusers
    private List<SubUserDTO> subUsers;

    // Converts Seller entity to SellerDTO
    public static SellerDTO toDTO(Seller seller) {
        // Map the list of subusers as well
        List<SubUserDTO> subUserDTOs = seller.getSubUsers().stream()
                .map(SubUserDTO::toDTO)  // Assuming you have a toDTO method in SubUserDTO
                .collect(Collectors.toList());

        return new SellerDTO(
                seller.getSellerId(),
                seller.getUser().getUserId(),
                seller.getCompanyName(),
                seller.getGstIn(),
                seller.getUser().getName(),
                seller.getUser().getUserName(),
                seller.getUser().getPassword(),
                seller.getUser().getMobileNo(),
                subUserDTOs  // Add the list of SubUserDTOs here
        );
    }

    // Converts SellerDTO to Seller entity
    public static Seller toSeller(SellerDTO sellerDTO, User user) {
        return new Seller(
                user,
                sellerDTO.getSellerId(),
                sellerDTO.getCompanyName(),
                sellerDTO.getGstIn()
        );
    }

    // Converts SellerDTO to User entity (for registration)
    public User toUser() {
        return new User(
                null, // User ID (auto-generated by DB)
                this.ownerName,
                this.password,
                this.ownerName,
                UserType.SUPER_USER, // Assuming UserType enum has a SELLER value
                this.userName,
                this.mobileNo
        );
    }
}
